# Generated by Django 4.2.1 on 2023-05-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_type', models.CharField(choices=[('romashka', 'Ромашка'), ('tulipan', 'Тюльпан')], max_length=100)),
                ('shade', models.CharField(choices=[('оттенок1', 'Оттенок 1'), ('оттенок2', 'Оттенок 2')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_to_buyers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_seller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'is_seller': False}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to='sellers.user')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.flowerlot')),
            ],
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')])),
                ('comment', models.TextField()),
                ('buyer', models.ForeignKey(limit_choices_to={'is_seller': False}, on_delete=django.db.models.deletion.CASCADE, to='sellers.user')),
                ('seller', models.ForeignKey(limit_choices_to={'is_seller': True}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_reviews', to='sellers.user')),
            ],
        ),
        migrations.CreateModel(
            name='LotReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')])),
                ('comment', models.TextField()),
                ('buyer', models.ForeignKey(limit_choices_to={'is_seller': False}, on_delete=django.db.models.deletion.CASCADE, to='sellers.user')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_reviews', to='sellers.flowerlot')),
            ],
        ),
        migrations.AddField(
            model_name='flowerlot',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'is_seller': True}, on_delete=django.db.models.deletion.CASCADE, to='sellers.user'),
        ),
    ]
